apiVersion: v1
data:
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:Jo22wBbUU+9U4oBNj8ij8udpl7q5yGISq6txO3y3g1qgmsP2MRFczZJ6zVQiHbn7,iv:FgHiFrDxKkMb55OCtjR/h5Naf0c2RKAH+V/8GRTHCLI=,tag:2liW2DWrjMXluAMD7rCgMg==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:cRoWj7YgGpcj3ozebl/4EhDgm3sgSAgrvmY4VxOxY2Gsb2SNVEz44uDDOTI=,iv:NFBA8fEP19fhkb7tI36zkByWJ2X3TBn0pKT/DVTw3Eo=,tag:ZA1l5UVtBWKc2xhbHVdygw==,type:str]
kind: Secret
metadata:
    name: actual-oidc
    namespace: actual
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0FQVG1kWEpmcTVKNTBa
            UVQrM2xuZDM4MGFENVJ5cDhyZVcxU1AwMjBrCkpKVStvdmdGMmdsYmRHbDJhRnkr
            MWVEMGwxNit5SDIzelRmN1FtelJjSmsKLS0tIDBRNnRtMmllSlphTmp5VE9ZVGpa
            N3R5c20weW9oR2NlaE5TbDRQK1hWaUEKCn4gWAcY9tVI9pV0MQqjcFuQfFiISYSy
            iC7QdbhfnICI3wIbyrANUB1t3bXGnnXLixgsrrAzaesBefrkawPAVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T12:31:49Z"
    mac: ENC[AES256_GCM,data:GAINzkYH8Wlp7puqGTsty7Tn5SJD1NwaBzFutG6lez8VoFdpYocdV1wfySoJFNfCIrMu/ypoWaJ1Qg8aINwZcgr0CEJ6cUL36yWwol+bf9lz2ysFO4ya5s5qmCXMTlggN3G76c0BZ64ZZIdn+k99PxUB788oDM2J0/XYZ+pVMTE=,iv:kSZUVFU89GGLELZ70urqEDlLvEjNcAd3LKBs1iQzQ9c=,tag:xoT8BV1vCeNTL/0oKomWuQ==,type:str]
    version: 3.13.3
