apiVersion: v1
kind: Secret
metadata:
    name: sops-canary
    namespace: demo
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:6fa0OZYGLmxVLue/umfUQ4SqsOw1kJS6omONFrJ1erfbvyxdo1MR9YH3UB8yEEim6bXvudloneG+CFg9YzbomWc=,iv:l/0X0mRmczdSdDTfzMWlhvNZQugIMhMlzqQA6nSMQ/s=,tag:Af1w7rqKDpJi2MNPpbzmiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Vld0SkRqY2tsVEpLNWtm
            cmxmSm51azNSdVRIMjdvcDBmZktIclV3Mm04Cll0ak9hdmJWOUpZaHFieFlodU5E
            MkRPSFV5SDhpVnhvYlJ5ZzhOOExPR1kKLS0tIDl4T3lwY0dKRDZYZHV2N3R2aEFt
            bU1CUzRZc3Bic2JnbytsTUw1cCtmSUUKxNBXsHXoAmKBssDdeVBG6XAZVZTOc2RE
            MwP5rejiCLI8DOfh2m/+F9gq5fuc5vZqN36M0u9RYLnykDqKIuARiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T18:58:08Z"
    mac: ENC[AES256_GCM,data:gbnP0hWOaowLkc2Mxcnhd2bdGM7ZoB6DnJ5+5eppK/zcpcGsHtqyVruTgfJwhqwt9tp/oZBj1L9GcPnkadpb2Hs2qSJyQNPngl4c/lgDaMMGnGI8jxm6DwkJCBHx9HkHWiPbm331LmsZ5i/BD3+wEwG/lDmgYtzFdq0V27IbVt4=,iv:mPOcEP24lJHNMpE6LniPdDsM363A+xdq5abX3EhBbIo=,tag:SJNg1D/maSOkK+tyZeKAvA==,type:str]
    version: 3.13.3
