apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  selector:
    app.kubernetes.io/name: paperless
  ports:
    - name: http
      port: 80
      targetPort: http
