apiVersion: v1
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:ROUHQZWDBRKts/ThhZ8Jk9zbv2wEooGgq3n7KnT7o57kuKgcqhEyvxq3nm6NqHZ/6wncxBJjhDxrtE2VqA50+IxlYsSJv5kQSiLgRe4S/ORq3p7/pi23Eg==,iv:3dpWxVagPu9M0fEc9A6bLFrItCX78B0hGCliQba3PW4=,tag:uV6BWaRCOBebiTlQ5A1R9A==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:6xEK7VddMZZrweDkO9z1Mg1DcwP0dBt1z/8f8+Ot1eerSsOWVaF/XM5G+zHpUavVDKNUXe5aXy6tTuX62T0Vi5xj9nLAg9eM+NYpStfKoTLrRC4opkSo7g==,iv:7VMowbQ3i1qZfR6Z8P7UlHX0INxNP/tPaxtq1Ebk8ec=,tag:9ykkupLCeu0chZ+XdiR8Ig==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:ns6iwqQYwfN4mxNlSvYIajy6m0w6BXjJzVLcNj86YnGiXL0Uk9zicm5DxpGDmLtMy2wWt61mGGBHiyqUhfQi9g==,iv:DlDdJXWGRFmHHesg4a1Uo35MB4RQ0MbukN9F0Yn3+oI=,tag:VV2LZReltVr4MZDUWwv/UQ==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:qHMoFYDYROMtyfpGi3vnVfbkBG8vRRibfAMCeqx/CHgKamKbdJJnoQOVNV9oMCnxpzCyEuV2wrBexlk5pfQ6UA==,iv:TNmmvHWJYS10zDX8IYYF1QH4bNoejrHLcE5QP7yt5T8=,tag:v0QmUl47yCe4eqP+uO+ZrA==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:jHiyHAq5XI0U0aYKWIgDBTqf/IxPXIMgaEK7HLSqslDt61pmYNGzJkA2vHDQ8ZI7,iv:Qqxk99EsRZ/4RPszS1ttBpWFASq2Q+RfM+VqHdHm9Y4=,tag:OuwO9Kq1Ry4mwwKrQNGO5A==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:4rpZglujRTZys+eXff5PQ/CIViqwlDx3DszM4d9melz4ySyDu530QpoD4Ps=,iv:768FPC09dubbbDTs7dw+3FGD9hKSZgMGUArGKDkF+pY=,tag:Anbj1V/yb+1R3CXYz8GpLw==,type:str]
kind: Secret
metadata:
    name: sparkyfitness
    namespace: sparkyfitness
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa2k4MjFFL05oa09HcCtI
            cGVsYjAwYzJuZEx6TXJtQWZEYWJuL1VrRzBZClNQNkZzUC9PbnJ2b1ZqaVkvRk1Q
            dVkwNzhWSHJvMDZLcUY4ZTM4VmdMekUKLS0tIFoxSFJPMTBmdm9RUzhxZ0Nyb243
            K2dwQkQ0TWRDMlJDQnJNS1FJREVKcDAK4eWqbjo8bCA1YP39AsTrED4cFlhAFC9U
            ipqijmh3KNj5c7u1su9ATj4s6OEWYTayjY8eComWlTerjYrosy9UcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VUMzcGIrV01WOVQ1S2xD
            TGRsNFFMNzRRTURnRytHTXpxVDlWQkhaakZjCkZrK1ZqaTl2M1dtb1R1clNvQmlR
            RzdhMTNkZ041NHAvQ1VkQzB1L1JNTW8KLS0tIHlUVENnamhyM3NJYVM5U0swdThM
            Y2VXR21iMFFmbHlXbEExVkNibFFBcm8KGLHwUC2UXrdpdF+AIuRTO8ehhAlE6QUf
            iqh1l5y+VRGv49tvdKDrC8oqLesNo3PBYUkYpfTC9jv8e0V/bFmJqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T14:58:09Z"
    mac: ENC[AES256_GCM,data:1wIPOH968kBczAwjhP/c7R+oCm5KQJXg/2DMygGv/MxKBr8qbSzAF62aYd8q74Ux2BlharrIAU/DQWFwG+xiKGH0SassHsHv7QNpIf+0GlVN/xLm2auC2I7jcPv8Y7Hp4iIK0k2a8vGx/VAcmWUNlHrYEv6dcLQJiMdEA4FnBOw=,iv:Y/g6yyg4czlqGwz0xtFg8xruC3UmxADiRNuW4psuZbs=,tag:GS3tTL2xHsk4Ve0bafpBXw==,type:str]
    version: 3.13.3
