apiVersion: v1
data:
    CB_ADMIN_PASSWORD: ENC[AES256_GCM,data:+9D5CmbhOfVkNUcyqlYZjCA+CdIHlOYuC11edR87ONYTELNuQEGog0JzhKmG9ig7LSDAXjP671LkAP6FW+mnVg==,iv:dGlQTjlJ6QRuKeXcx3Uoyy6fBUTzY/aF85fWiSXaELc=,tag:W0AwTEQSi/DSgLNubEN0fQ==,type:str]
    CLOUDBEAVER_DB_PASSWORD: ENC[AES256_GCM,data:n623DoNEG3SwJEk2upzr2Why+5+8E3PLsB/CWYdr2/3QlTAthJz2haUJrrCNtnAAE1/kYXhmTJJWDCkZFBZZAg==,iv:gBseuHnygyt+EfLorMfxNfKl8Odrf54AgacbApQgq3A=,tag:XRUNUQEyBsrsY2bx6QT2KQ==,type:str]
    INGEST_DB_PASSWORD: ENC[AES256_GCM,data:9YRECm94fQQw4hz0zlhiDfXIBAe/oUMI2Erp4knkYznRrrIKPQbtFKX6SCD9Q5cEjef7C+HvrgqZFDAZVVtdOg==,iv:1LCTcNJgtht33L4Dged1fnoZJJFeEXDqfcSTQ8iJDJc=,tag:B/EnD/GGYQ+b45SC/owJjA==,type:str]
    READER_AIRFLOW: ENC[AES256_GCM,data:u08sB+baZ6OpA3B9ULRQ/zUW862vSIKRm6lcWXBQoy+FN6HfDNUcg0A1VufIrwFzYX5KqPGWyy9C2SYt78FnSg==,iv:K1W0+KN8gM/lt/ukmTI6NthkbLWmeAkqW7JiCF7JT/s=,tag:vq/HPgnt/CO+WyBoi1YwQg==,type:str]
    READER_CLICKHOUSE: ENC[AES256_GCM,data:svF0JIffRHk2EK/h4oU9MYI+W2g733ycVH33Nr6tM8I4Bc3DrKmTGlBBuNzplelyhHTE2M7zNw6S7nhifsHfsA==,iv:MyPGEP2jfMOU5Zde9NQ3+0Q6k2MVIcVf8MIc3th9RG8=,tag:HZKMqRxiiQAoEuzaYc/dkw==,type:str]
    READER_DAWARICH: ENC[AES256_GCM,data:YxzPD6Oct9XAUjQnxri/Z/rscXwuFCc2sHbsnrbYwmddqTlO+18n9AibFmdK1DV5awFnjs3RHbwkNtEBScgXVA==,iv:+5N6/FENoFQMEM+iPIAKwc+PC3JwaTr01J0haEAbktg=,tag:jWRESIWislJMAx9lYWr72Q==,type:str]
    READER_EPICURUS: ENC[AES256_GCM,data:OmtGG4VI/ZLrO5VG9nfouiRPyBD21FhUpJ9hO7vYgVTDuREeTwiC7c5Dh6fjZbqnijfA9bh6NjBnnq7ljvI+6g==,iv:VwHbFBKAjmKuQbTFInBUbGvJJ20YBE33IPaBdYZu41c=,tag:HFYAc6wZIAH9Un1faHSZKg==,type:str]
    READER_SPARKYFITNESS: ENC[AES256_GCM,data:Gf/K6fWvqb9j7aSNhCU7PjT5UvhVzI1rFc+9doaQYZjTtnm4ql08JI2OOw9KTORcaQ9nOl3G3NwsNQvEDwuu1A==,iv:RFZv15iYaxOGaR+2s5LB6HGGGWOnZklFV5FBOw0MwNY=,tag:lDBv9GELbgFzX2mKEYYeLQ==,type:str]
kind: Secret
metadata:
    name: cloudbeaver
    namespace: cloudbeaver
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOXBLSWhtNWowK1VWeVRU
            WWFJa3BWcEVnL1QyQWVyRjNzK0dKWXBxQ0VjCmtSaklQczI5QWpEUVZsek01dWpz
            QW1CWGNJejd2Sk80b21Qek1ZQTQrK1kKLS0tIDQ2NG91UU9za2YxZ0FZY2FvMnVt
            cEZtZnVMSW1wWFpJcG1aN1pNeTJ6MUUKgEu0HDMvs7Ftvb1Ry44sKjrtMj1GyhCF
            0afSh1DN2JBeHAOR1aixCFOgpKlprbkXm2BEdomPvTFgH2cLNnjoeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc2QxRUlURkY2NW9NeEVZ
            VmZTTG1OTWxyNERZdVIrTkNPUUt2TDdwaVhBCmpybGJqRExTN3BmUEF6MGkza3pl
            VWVBbGpEZFhqUGpoOWhmdDROSi9QVm8KLS0tIHRlTUxOYnJkZXVjbUZmZ0tEN25D
            Z2ROb3hkcUJBTVJtdXhFUHVoOFY3bnMKyfxfaPq9RW4iMBRLQLUlJjIXu1jV9vDY
            SfZdMf1pF+yuFXnXIcr/5VwAlqLwsugeHyz7X4QfAhl1+7GeQNEdAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:31:56Z"
    mac: ENC[AES256_GCM,data:cyEE6gK1xnyFP6k45ndZInYSufKkbfzlniccd6iaH7Nc8yqC42AUjzXe52/3XT5qG8k6ZAwUF93bkKV5qxN5v0XLHO10QA5zkqka4QmxDFbQEsrAGELBIHXKEGCS00JJP7LaaKBLXz4lNRp7uFlX3zoM5TrrD2rhRmTW7uKbnR0=,iv:3xNX/Q2wGKPnCym5bY5vEXkjvbhvMg6wKsTMgoefbkI=,tag:QTTKyi+2uGsivWOhyaxGTA==,type:str]
    version: 3.13.3
