apiVersion: v1
data:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:hfdvSdor8ms3zKMx7pHzPooBPQXNm8dgn4WNXqdwIP1+O11nk6PttNZehDr/yx9898yRRvTn6ovOXM4XSUsgDQ==,iv:BYXFrvomWd8mn3O8l0gvzY63mFyhticUY/POomVUjfg=,tag:wNjobvu5sVah81341kke8w==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:rWOvKZTks7MhDVtT,iv:FgjBdsSvzk0xD14EXRhvGfBONiiXngh9FNf3I3YA+QM=,tag:qOx+1EDyBRjf6QmCgxJpRA==,type:str]
    NATS_CORE_PASSWORD: ENC[AES256_GCM,data:/3TxlJ7bYYAJFU4ahWpRul77ejj901LpiCPqK9LOSJMTtkKEmxsPz7xUCYj7Vukhz+k9gCGEXBCyqbq1Hh96NQ==,iv:Pkrcokas1Zmgv5tX2isInlEKO588Yt8gpZukZIi3I94=,tag:fOTijkBNaheQ3toIFK/ugA==,type:str]
    NATS_MODULE_PASSWORD: ENC[AES256_GCM,data:IHYk/80XbseA/Br9OGQyAM3PVTM49gSEACNZ+wSyy8mORc2MZ6VAJwohRjIUzNOQzEUqcJOujdxmXuTcyc4f0g==,iv:MAFTXks2gnErvy3jGay1IflDTcy595RAw9jP5gZy8CA=,tag:qmOZP8m3G58hlBlBdQ7BDA==,type:str]
    NATS_SYS_PASSWORD: ENC[AES256_GCM,data:YGHALlS8bw4OOSniGeEgn3aW31PK8Wal+u6QJ1fJu5XyV4MfhJpwI+e/3+jiLemnMM325hpa4TXtysEXXMbrww==,iv:XsWswICXvSrRt+bNZZn/u6Tusfx16NQUBOJgDhFZQ0M=,tag:Jl1eQfrcqk4MrgHLiKPXhg==,type:str]
    OAUTH_STATE_SECRET: ENC[AES256_GCM,data:UGsEKMBdelmyA8oGkqqlARAjIihQtVBXFoqMfQu/0YhlrU5GTdf4wrkVxiKd/rHZL0iGOD3DlweLTRXeETySFb4YpXOM/lQCc975V8LvMdgypMp3rCB3xw==,iv:Qi5tp84C0ipkC+j95afIXifRBcU6RjiC+q++A75go34=,tag:rtIImvqYDmiXL67bu59nlA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cVRdG0vDIlt2yCT32tfFdqU1QXDJECZfeaOJiCvO/8bujIZPdP0KOZdl2qtJmMEN65pT0Rxs+mpOa905UV70dQ==,iv:AXvHnxP6o2yrdlf+B5WG4ZYjoIO+3eR5uYLBkq+u8yA=,tag:+2J+7pHqqdlrTr1CgJkycw==,type:str]
kind: Secret
metadata:
    name: epicurus-secrets
    namespace: epicurus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU08vYU0wazQ2eFJlNGZT
            NlVLMWQ2eXRMeXZkQzZqaEJtd1BMeDZEcVRnCkxMbkNvck5SNnBWTHBSem9RL2Rs
            N0YwRk1Fa2kwZUdCUDhxU1BUS0UraDgKLS0tIDVSOVQvQjdXVW1sNUh1VjFVVlZQ
            TDRIaVJNVmJqNWxGTFhKVTVuTlZRbEEKtgrESHu/DQQcUgIsH1dwczFNWm2pZG9Z
            LgoKxtaNyW6cJyuxd4jrTQFqTlfQS5PG74S7CNHHNJQi4BkfTINkBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:18:50Z"
    mac: ENC[AES256_GCM,data:Pwg1uYkr/S4jFrdalsDywSUV/u0kf+SFV0nKbvhWj45YXST1L4Dp+qwcUEria3spZHHV5TCXzuc3229bRF3I2Lp8syETUhEK/ZKJ+CH1XICKUrmwIHcCqqdLSClfldwaIjwPmc1cIRcZqQN4t0j+OLEUsfNaE5S/5q0Yfhculac=,iv:9Dkm5DJZHferrsZDS6nqu2B/w5BpXqByZ2guxtypJpQ=,tag:9hHZ0mA5L7o+ANgWW+8R6g==,type:str]
    version: 3.13.3
