apiVersion: v1
data:
    url: ""
kind: Secret
metadata:
    name: alertmanager-heartbeat
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3l4bWtralB6ZTBwSHJo
            RnBtLzVzWERpMDV0emhJQXNHN2xiYlBGVUIwClFHTU1mdFcvT3RWTHk0eHZOemNB
            NDl4VEFkRXFnbHR1MERYY2lZWjhOaW8KLS0tIEM2aUR4dEthREdDU0dWNG1TMXla
            d2MzMCtUZFg4eFFURHloTjUybS9WWUEKB2WnkU6JIUZFHjJFEskb3D6Nup05Hvah
            relfaAtadwKYBXS1KW03QdioNa1x+4p0AN1cvpMY2W6AGh4iZ5cVOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:38:09Z"
    mac: ENC[AES256_GCM,data:UFFcQLszKOBEYW+oqbPxi21IWZXjRSTz8f3EpQOifXHD8ZmA0y3ngbRbnlGxjWwq33zqMalU8enkeeGyVSLPWhPw7HBfzkXK4ivmWUEhvat61KhuL9ZTv2fFepUvkqVigu81pbqxZvrgqsXZ0A6WOKrMEpSKOkAy7kbLOiyPh+E=,iv:tlDNZU4mgD5LoS5VHyVLB55wwTCOxZcIARlKsjEvnj0=,tag:fZh0yg0pzo+iqlZdlmw4hw==,type:str]
    version: 3.13.3
