apiVersion: v1
data:
    url: ENC[AES256_GCM,data:nlV3jKMgNAF1Nt3fMztrZRtddCi/RyI9qJJR46bpg8yXfcVhi3qHp3R4+GJEODgi/lX/hmaS5QcD/yqmPemABoUD9erW7GxNgLloow==,iv:VCiGh4IpgQrNqCVWc1LUnK9ZX8aE29mrNMTk3/Fg9fI=,tag:4P8r9zWDFkrYfUZtnTPMzw==,type:str]
kind: Secret
metadata:
    name: alertmanager-heartbeat
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQnJyVnZHTWNPdUFJYUd2
            WHQreXFjM1ErVDlCNkpJRFdGNGNoaG5CelZBClA4TkE2UmgydEZmTk9jNnlVYU0r
            dVdHM0E0TEZabFFCNmRxNUV3eXRIM2MKLS0tIDRsMi9vaTRkQTlpVzlBV0Q0VmE3
            TzNRMCtaN2R6dk1TU1o5aEFPUmtCZW8KwagiUY4UCLrqt0WVEquEkSOxqMAjnx8N
            74hNLMVz1mRxlC9vQY8LorK7rPMtE28BsVCVg0/7eIGzya7mXjrcog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUHFLZjlvSmxvR3BLSUxk
            UWY0d2JOOHY2aGRoN2FuME0wWFFwU2NNYTFjCnZRWTRiQ1JwYStwR2JjeENjbTRD
            aDZLc1BXaG5BQ2J2VDMzRHJXSXh2eXMKLS0tIG4xUjlvTjJpdmtSdnIwcGZuWU9l
            Y0kzMVhDdy85bld4djM2RmxxcHU3Ym8K/2Gsc5ia/KYOpHup2OW5uureoHoBNAPd
            2tC0zemG+uQPOa9H2vLizEe8YosZRaGCAYqwpSUQcBV4RIwnEy8+VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:40:50Z"
    mac: ENC[AES256_GCM,data:HfuMoh3c6AZEBwBl4s/zjuZBqxsrH/qzfpF8qvmbTUaxwbTJSXzQDnfojckAJPC4TKVxUfxCZ9jZ6DCpNJ3lQJ+M0lTBVveC00FwUHxPStvdIEs1r7vD8drNoE6G2KMWJfG3m8VQ32hTSRmwOn5CtwZFnGYCZ4VFo04qOL5DIo0=,iv:5aUl9VUr8h9B+koa8uh8hLqc6ReKnqQC/8yXPVd+twE=,tag:iqp1mLwqc07Lkh0+AeYe4w==,type:str]
    version: 3.13.3
