apiVersion: v1
data:
    HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:KQsBGbJ1JlNRfWOmhUAU4LFsIgzSJI8TQgAtMSE58huIkbs66UJiQzHo7xO6KfR9,iv:L4ODGCIr+1iZOqa4I3Gg7Kzzgz55NCRgalKp8MPjoqc=,tag:c62+gcSnMlwpYAJbX5Ddbw==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:P0VKeaQTG3purjrJmY9qsLfvc+goazGTI5uEaDdAqs5ENhONav5Fo1OKKeM=,iv:5bfMptaxaphT5WOgxuQrz38l6tGzC0L3TDb+1Z5vMjY=,tag:9LU2uHouU8SHDSnI0bSzJA==,type:str]
kind: Secret
metadata:
    name: hermes-slots-oidc
    namespace: hermes-slots
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOHRDcUFsRXBPMmZyZmoy
            REVDeC9tT0RGTEppcFZ2enFHNVpMMU13bmdRCjhjY05yd0tIWUlNc01peG02Q1Bj
            VlBaYzU5VVF6Z2VLZXlpTG1jdEFEZlUKLS0tIHQ4QTdRUGwxNFBkTis1Y1dnVTVh
            VTZyRzVNTmFsdGh0MmwvczNFV01Sd2MKW6IdPv6xehAfUJGQ0GuMHV1ThQwC6gjD
            6a5Ir7XxvtYydqzsyiHND1IS5dC2DGI9QgBumLDkPCXcFqTDxU5f1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T15:53:56Z"
    mac: ENC[AES256_GCM,data:Kd6UJ28hkCcxK0yE1WG8DG5yA0UBpqUcwbjQmlFLeL6Gu9fjX7LL3jiX8AV+r9vDz1RYsgQspn5a+prnc94VhLvdjZ3UTgd/DADb8tgZ5ffePv50C/MEIMW9yj0libcfLkQK7dlExL7dKXGwd/h2z90meklnKkqKYOCcpOj4mvQ=,iv:FCUfyKuqv/tC4DuZdxYqZlybTQgWalkMhcuBg+oUD6w=,tag:o8klip0R60Rhg9G4+jdBaQ==,type:str]
    version: 3.13.3
