apiVersion: v1
data:
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:upKYmdCFlS8nqJ4ow/Bho2PiR+sbIzDYkdy1bmLtuSu/+sdNkE5lKbjFOUkkZg8oHDxLjcuU6k7dqH0i9m5EXg==,iv:ydxDx+/AbXoz+YOOLqXWp9qMTBugqJCJJA+8mwYO3BY=,tag:ghCOpPYLQaEOFICE9XqYcg==,type:str]
    MEALIE_TOKEN: ENC[AES256_GCM,data:WtwNUxhhailDTbHKHr5LEJ0dx/EmyL2Dr9uEaUnCrAzOV1QqOBVTpWikZbl9Dd6IQqH3KcdY3Uq+lWiFmsLY0mzPV4WI1rhc5JJpYezvwfddafcEYkr6r+CbYpCrljYDfd4MXAwBSFQ8MMw8w5RDHOAaUEdX9olVcldshDgLRxki/vCC1nPhp+XHN+N7CCLobvVH0Z5SN9A2nkjRM2vJRuEzB73wczudpj30ubF26Z0V1nb/0CyztL1FHPzZlc5rHuIfQvNpwAIsfWLnUxr9f6uuydFL+alI5FXeQtsRBycbt8Rd9OyuYq3qe3QULpPykSQ5QyME5uCOJ3DWn0POt20wZ+pduf/cRMr7FxcScunwKWtFEFJW3W66uA/uYvKdNQ9cBgl/yCuz/gTx3qS8TT9tTYz93gdhl4o/yX+X9P2WJWNVNvdd87O43RfBJo+EHLBorrAQ+ZLgvR/tra9oXo+NFdLG2amxftIl6zl74lH72sJlpCSbExUvFNQFcdz4e6Zp/YMMnMw=,iv:eoZfKMbPw60sGfWYUPU1iKYU2TYMi5UYp68SICoxs+U=,tag:IRUHm89Yi1zDDf5JIQzrtA==,type:str]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:5pu5NI6PRvJd3JL87sfrdw2ZGe/okiqyqZxPNCeBTm5NNd4KHZcwffpuMOubI9j+J7cIc7XO7dw=,iv:GOwnqoQUQ8hiTBYDHSsapWJuTw7++zRpRRSfppNmCEw=,tag:VsQ9TUWOE5UIz6hYBt/USA==,type:str]
    VIKUNJA_TOKEN: ENC[AES256_GCM,data:ulWg+WMI60pOm+jD0OKZvbphY30ruNzT3YKhMC9eSM367Snxrdin9ZwshkwYoPPZX5nvDcMkJMmB57bP,iv:JxCg82CdG9xZkUpnDdCgVR+gh8K0t86g7Thls18MXvo=,tag:GvqhPcUD49O5xpykCDnyOQ==,type:str]
    SPARKYFITNESS_API_KEY: ENC[AES256_GCM,data:+7LSrcMRtKizGtK64jfhmLCFqlm1uUQ7Xa8bqdPGzP5tbC3D1Ei5SB4yuHLDZS0uFEYQ/hcv+IORpwOSbZjeYQ8Ud8IJ9N0NiMRYnsZuCL5FVMRBG0rwvg==,iv:dGC8kp+tor4kDJkj+k3DZbKmAD6zuUKq37kmvF2SubE=,tag:BP6jWtiPVVFtS3YmBY5yaw==,type:str]
kind: Secret
metadata:
    name: airflow-sources
    namespace: airflow
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZWt3a0k1dlA2dWZRalJN
            L1JCYi85ZFdCblEzclhHc1RYR1NaRGphdlNNCmdUWVV5dndDY3I1UlhRU040aEtE
            cHBPa0JvM1NibHNiVE1jVXNWWGZxbkEKLS0tIGpMQ2NNaWNlZ0xpY1R6a3ppY1VL
            RmJRUzI2QUorZHBLbGJKN2paZUFOdmsKJ0W669oaA+hEjQUatERzS3mtnGCnTVYe
            ZiLgN3Zy/e4TZsJui/b/eKHQCAyKXBnPaY3oWMl/HWNZTH6umL/pCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXg1NmthcHpQeUZJRERq
            cmhZWGNCcC8wbGVuWVM2K0w3TG9SZnN5NG53CkdHaWFiUVZTMlk2Vmw5QjVhenlo
            bjd1ZDJRQWpibnRnTG1wcW8xM2pNd1UKLS0tIFF1d21WQm4zbU1ESlBRU1dibUVq
            K0xlS0FQOW83S3lGNVR1cmlPZjR0ZkEKePjMw+eKc8K2zFbMpJF/NvrF5vrS7V4V
            ge655Ey+2JAGwcYLVhxG8dv6T0fAu1IWXC/kqGygjjpIRRgxxzJ88A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:22:50Z"
    mac: ENC[AES256_GCM,data:QR55PGncqKWVrqKE1LwP4vvzLXK/yitBrS3uKiYGZuWfBu3l2tq9GXxmk3CHHeLAzvcCNSEi3CVXr96WXhCb5W5V+mcVPhswwNzRCxqCrJEX4gNNrAH2kTOKQR9y5cHlJJx4UXe+S8SDHWf9pFX0ybMJWV7zkn7QfsWSQRnwwtE=,iv:EudCCWRcPB7bnrL8Ni+k/euXYWgqMrJWfNqCPn1wmbw=,tag:YMg4hHnIJyEXIJxeQr/Mzg==,type:str]
    version: 3.13.3
