apiVersion: v1
data:
    HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:zWQAzpJvRcaR0wsnqmsQ3RLiQLHpD9daTucHCECMVrsG/EqQlc5cuz0VHng5G1D6,iv:MS1foO6S6xN2k0mE4eBnEh8iXzcjTzk6FbcFsSEx9cI=,tag:NC11Op9NKmWQ4EC+S7DErw==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:smcqYblmxD13U0OR83c4ohk+ENAlbFQQVu7tiEgEjaXn3mDPgbBVdK/NPlA=,iv:PV8bxZbT4YpNW2LQe7s69M5+to2epee2ZxWtDqhI964=,tag:I9VsN8fGFlFPboZZCkv44Q==,type:str]
kind: Secret
metadata:
    name: hermes-oidc
    namespace: hermes
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeHJuamFaY0cvYktnaUxu
            ejBjV1NkQWg1ZGVJdE5sall4YVVqMEs3WW5BCmxQelBiSU02YjUzWTFoNCtzK3h0
            c1lzSElDOGhoRmVVU2dvYVhsTThrZTQKLS0tIHQ1REJrOStvV0ljdm1YcjNCT2hv
            Y09UQWJFYkcyNml6OFFubHBFdUVOTXcKvfJHC1y/VUlm5HotysrdJVVQywY9bn6L
            ajhFJ4NZCXBSf87Wce4YPwrWF9NAifVjAtZ5OpA3roMq2brRSXVCnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T14:25:58Z"
    mac: ENC[AES256_GCM,data:yfg8iiJFnqcN4/f0KOYrq7jMGNeW30yVIVULSs1xDQ1Z6zK7lNFU0m/hbh8E5ZfPDhHXqDFQrZJgLHbXj2Z6bs1ZewB1iBx4qlG7umN7OTw6KGaXqhQWchDZyhxf0uMM4kIHZyzQVI10OcY2s3KonImhsPID9HkEdrSpIyktqCo=,iv:b26nycK2gw2z+rOP0cWnVPZ9PEC7Y6axrhSIzc8e33Y=,tag:qtFFWiNBdmYNKP4xEuBrFg==,type:str]
    version: 3.13.3
