apiVersion: v1
data:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:cMgP5JzKn6zBQc4J3dcE6xp4Fu6qTLU4JV8ph7AXzY/ohZhwnZtRkHiTPSMEqyFMAKqH/nAu6ws/oqN/pbDKNiR72APFGTXJX+hKQ7OmFu8/I/daNYsoSA==,iv:u3qoZmLj6FPV8iSdWSgJAQXSaEHPHygfgX3HhBNsOJA=,tag:DOSJvvNRwXjdjjnNIFnnaw==,type:str]
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRnJzU0FsOFBGVjJtQXlG
            SzUrbVdEbDJvYVQ5QldNWUtiN25raWZTZTFRCllVcStxeHBaamxLTnRsa1ZldE4y
            Ym13NDJZRHc4NFhPZjZpTlcrSnFDK28KLS0tIEZTcmNrSE5YRHVQc0l4K0NvUkZI
            RCs1UFNmT3JxTGREeHZkcnpVQlBLWW8KhGmX7udxoyjLg0AlIKbsiGqQqMXcoyST
            W2aUbS6m7+/hDtxkF6Z+n845B+gA6bq3na20Kxh1jyT2xNcZn4QAlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaWFQRWFtMDU4TkpMWGZP
            SXZWMzNSOHRmWkdCa05nZTNPa1pFblR4dTBFCjBiT2hqZEtHeGZmM3VrUWY1RHJR
            YmViSXZKZTZLUTk3cDZHU0lQYW9uVGMKLS0tICtTUnNGNlYzZ3ZvN3I0OFZBUDNw
            Yklqa3REbXJIaHg1MVEvbWU3V3cwMzQKgjgFAUVWyM7N+x1fvIJar3g+gwEACnOz
            6fDRxMe4bxoZmFO+weUHmMZBAZzqSEXxDUtvnaInPJOTWz7u/7w/8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T09:43:07Z"
    mac: ENC[AES256_GCM,data:Obfyrem6PusJdBz1pnJ0vsLwmwaskCZyuuwshSIBrsS+P/8i5BnEuy/hAasS2wFKQR2yK5++R5lFatDd+VVBcxw2v8cq0bmmQKpA3ZBXmjZ6n+D+YmHEzbIo2mTBagmqK0Xpkkcu0IBJYQAT0h/sGU5tr+CEgIs1swECEpkE9dg=,iv:6L2utWfavztWPe4CbaW5lCB+11q2Q2q9kAHcDDCWgWY=,tag:f/D1uLIjh13B3WRk1hK0EA==,type:str]
    version: 3.13.3
