apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:htCWaK4=,iv:cBoYJnERxCo6SrKtb0Eh1S6w1EXUdQ130aH12QCE0xU=,tag:oylGJoD7Xl6yoL3ciNGXMg==,type:str]
    admin-password: ENC[AES256_GCM,data:uyUtwP57Rw8urfT8PPgDLWgdK4sNLpK28aSrtZ9lwd0=,iv:Oa7pkvsOEKGpJZHrjXSSSh2IrDNDfmaUOMcT3/chQds=,tag:TdLShxVyRVN2Oua/980Mjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT0c0b2IvelJ1aXRvNTNR
            bXBQYTR0dUFaUzNvMy9UcVFobFhFK0hGT2xJCnd2bmpDN0JDODhKaGIwM1NaTmZN
            eWdRMk9WcjJmZXY4YlFFQVJ5d05GbTQKLS0tIGZEZjBVeFVJMnI1azFjM1FteGk5
            Q2xjQmRVZkVjNGFXUkFOM0I4dk1XV3MKUjVMqZ52dmvvGNWuLfobxZ2lmXfsiJq3
            Noxw4o4sZyQ34bLOkybxBrcCXIVaFT8cOpL0WnZGyPBc2mvnvDoNxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T20:41:52Z"
    mac: ENC[AES256_GCM,data:iTcfWlKPc9lXr4d4/cjN2S9FBvId/cmy/muN7VvlhBbmkB6CeObiC7cC/50bVqUUum6QSpEw1WYd2vgqcEFdB51B8YSm8PszVu0bluykSKT4DIQ+jqJkhqFxOLHZD5dMnC/6c3hpFZlJC+VlSDSmFYjpim7hCR/5C7ch5jAdUZg=,iv:C5mSLxdcbEj2GwiURrB0x/WrhlVMY25SKvwqcaPtfCQ=,tag:bEAoWiGz8jieBDaJAXzpZg==,type:str]
    version: 3.13.3
