apiVersion: v1
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:hK7z2c6vPy6AKSaASqswTDwYe9ppKlJw/JT7wdTEDippZkA9Mpyqc/34X0oTDA3I,iv:ygJo5DqtOaX+1+FO7kFNmRYbW0wwtXMBb55XG/oavCs=,tag:Z2n08nbFOd96wKKoruA5TQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:1t+9mZ7EAU7DoKdVZ+h4Sm8OOwCn+XJYGQulyuPrpeFetOECLvH8aS11l/U=,iv:WV5LgAw2GGT9xI4ZAUZx+yOTsoDfPqeseoPPBLjMfUU=,tag:It3HJGFmNqiSt+eUWLNZoQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:FZ3/Mdx88OYGv/rIM2lPabxNX84M3MT5unuRk6JXGpHpdYj2f90lSjB7xEdft5bCfIHA5FRVHtj19X7W,iv:k2+/hCzPyV/D9wYMT0Pusk/2+JiO7ThYg5VwhAeIics=,tag:Ry/uo2HqA1wTB2pEmYKSzw==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: oauth2-proxy
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdVh5VFZOTTl5RG5rS05H
            M1VkNFIrWjRhUkMyTWd0c2lkY09NTG9kUkRBCkRJMTVJY3E2WDFBeUlLcGhaMDhw
            MkVKMTNiM21LVk1GSy9pekJ3NlZOemsKLS0tIC92NE14NVVFOG9TN3NUKzhDNjBG
            SVBQc0dwSHZhSGV6emJZZThHcVppMWsKJ0YzMKadVaLIC9AvlUUS0D8u2W4GfcqY
            O4xdVPO9QEUOaJZm1NAOmTvXsgI3q8O//x3Q2Ui2cUKhbtSFIRdM7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T20:52:42Z"
    mac: ENC[AES256_GCM,data:93pv4cECBX/ON2M0oTGujSKx/U4hW2UPX9/SBt0na2XzoVblN0AzUfrzej1QDeX/z7f/U3PFM4WBh4DNVd96YGgYJNsnAx6YONX9bdsUG+rLq+0WTKzPJtx3dMoCatHQG6YLt25VpEDLuNzseh0PmWmjzXboLH+1oryTCVSFiFE=,iv:7ONw5gDVjbvkLTw1CBAnGirNoFMe5pvyjiImsoHfTAo=,tag:IUOjRtyaiN41AdQ4fqKizw==,type:str]
    version: 3.13.3
