apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fVCnbgWm/yzrAuNsoKbHOmA6xFVxvyGUAE1A7g==,iv:EzPAHpHQr8AZiH71GdoY3rCQyJixLBQftKVHwZfxRGA=,tag:5xR9J+74vEaSDSYCDqLcLQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zbyIHUQ6xgUg0VAECNuZdF5dCEqIJBZ3G64jYVk3bPxJLOeTD4o6fGAr5VVZB7pjxt7gSu/dxUg=,iv:7CzmH3gtu9ZGHHGDYiRnGOTJ0pgJ+Z0UInH3hU4E0nc=,tag:6K6Hjy6j0d1LhYFcScFlxA==,type:str]
    HC_PRUNE_URL: ENC[AES256_GCM,data:7NuA3Oi1jW1nINuWhZRvckVUHCJro+VesQY3Vo1uW8kffp9Fl8zz7gC4/8A8QxOroFcj/YNxgGbHNHq1NxyHjhYSZ6Q548hFe/5C2A==,iv:qPV3H0/9nAQyZ8/x5BL1XtTSNMCg64afBcY2FpuT8OM=,tag:WgiqxXS0ApT9EzpbQ6chPA==,type:str]
    HC_URL: ENC[AES256_GCM,data:Dguq4TU2yBbffKXk6vi0KVk+3pQNvkxwjWvjxm94aTsyfj4G8KhAyEZWV3ohboh+mIHj4FP6ggGZwuePbnarzteBe/awUpGp3cCIhA==,iv:6nWD7A/t7P5M/vc5cWqzqfeAITgiBxqEpswX057qCHY=,tag:PMefREZdmGgKm4jAfqw5IQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:R7xBilFUtnzmZNSnwX2anINR8vfb1cnLEwiZeyVqUMwOJbydOk8a8BvK5D+GBw2QV7g3cyFCBjedJYG/,iv:g9Hy9hct0nAoRC6L1wDUOs0O1UG03rXlYy8VNh5tn1Q=,tag:iLvGtCV1o88XZ0tZ+YqvSA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ZaipKMOk0VwwrBM6xbsPVLh4eAjvIXch5qFTnUCeXWm9ODM6fYg48Ua3+OpmKBamIpCAc2480qUJN/zCoJ3lKPw2p3UIDpBQR998cvKmcQ1Vt52T,iv:aYqU5RPsG1O5I44PBCItwyxrc8uOGxJQD9jNR/FG7wk=,tag:GcIutEWfNbotSfNGq3BD2Q==,type:str]
kind: Secret
metadata:
    name: restic-repo
    namespace: paperless
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEtMRUlzWjY4VGphcHhM
            U3BTTk1uZHlDN09lQkRpOStNaFEyVUNwVFFnCmVYTi9ZMmtpZlhFM1pOUzlJZEpV
            aVh3eHhLdXZEUFFRNDkySDFRQ01yWWcKLS0tIG0vckhpNytIa1p5OTJkeGJmOXBz
            cVcyRVY0bTM1eWNiNUtPdzg4UjJhV2MKfjbE2vVn5Am1olhqAGTX18bccVw9yjdr
            1UtDGOnsy8QRpeC1gtnu/eKz8O/WPzwQfzuVUecX83neZPTmps2+0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabWtXUHYrR2JVMnI2aWRj
            TFBMbG1OVS91WHhZaWgwRDJSYkJwY0YwS2tjCmhJdVI2L1BoZGFvaHJnTFNneGtq
            S1JMUGZWbE1EcStyeWR6QzQ0MVpmOEUKLS0tIG1wM3ZYNlV4VkxOczR0TUNyNUVw
            WXhIRFdDM0hNZmZwb2UyYjV2S3M0cU0KUxJS33Qwj0VeK35padhduwvnnLF2c4T7
            200H+c8h/jdssbpEmhBPh079MriWeO6guiEZOcg/ufPLJRga5mitPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs7j6rqdtw698l29az54ltjepnflpa5apg3zwx45ehdtwtfe89kqvj5mee
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:35:06Z"
    mac: ENC[AES256_GCM,data:BAo3jT0O2DWfe+MfVZiiRmK5SwNwv8+2P5Y313PNuNGpnq4cgZ/h62H8hZjyF5ghFXWorhQi0Lyf0xH5kKJ+bWr/5azGy8SUEb9F//1bBEBLLXE7Mgz7U8g4HL2iapXj/6XBI1eChTepBzmeeSUliB3Gmng0z31u1UpXubsBnAE=,iv:3hEvHR0FhJYxHyvOY4RIlNAVvvTkC4b5v0zrfFHtm3Y=,tag:0spFF+57tN4SwB2u/OxFKQ==,type:str]
    version: 3.13.3
