apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:28+O7KYzgI9zTOP3VNSbA1/JgZCVYhU9Gu8/PA==,iv:ufwH5YlH+dMcXq67EQeTNWeqPa5XJNubnK8+9CNogz4=,tag:C7lub+CzFQvJ8CFPqMWT/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:r6EpvOOEgo6TFzXfEf9483a1oBdQFYLVHYbzWR7LVpdK9OWl2Q7BOn7egNw9t9cEhwOtq/Gj8RE=,iv:UFQE0kfMbzkIv4qX8sLNP6UOVx91T9nFR5JnO+SwBHc=,tag:vAe0WP7WEYcJJ1cZl+pnxg==,type:str]
    HC_PRUNE_URL: ENC[AES256_GCM,data:cojlQCPybm57ZMRsOpmnLJGtbZKlxYMeAN9KN9uPMEeV0ro172C+8B151bDToygLpXjYXIlODhGGBR2o+g6rsCxoc67bXKtoHQ9f3Q==,iv:3cdX6sSG3uO+hT4k7nRTA+a7VgJXujCU3r7NV7nEA84=,tag:WwgphPdqMju1p1NveS0NMg==,type:str]
    HC_URL: ENC[AES256_GCM,data:GHZn8RRHUlKDiRrdUTfMylY0q84qWUbVWtF7yPrsjVVHi8CWIVRxeQKNYKFhlcHVAbv+aFagzbuY8Rwa/q4kgF+7x8YzIN76rpFW0w==,iv:HtaIvHalLRJy3vvo7KkL/L8N/ndBknfSKh+ljP7ooLQ=,tag:MbfrX2sg7LobpnmKU2ErJg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OAySREHNGgUidH8yx9cg2Qw6SaFNer/YeEnNQ9XAObe43a7yrJDU80KxjqPRGnnfcbjbGtdnW2Pu4WBf,iv:uNkwP9QaacJ4yzP9eowkDOi33vm1K93lDDXA3MMT1eI=,tag:Tcxm5WNkR8hQQpDhJ/w/Dg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gpjOgpb2tmGoXuVlWmLvvFGaDQu/LdN6g4UYQjvlgyffacdUJ1Ao06vYEnroJxqngbKgTSmri4orOVeXy9cEO1RTgz/FywvBLwskUL+891Iqb3C0,iv:uHz9DuXHgHXjGhpUaJHdvCZVFzF0RbUM513SM8FBZvQ=,tag:5qfYJrVO35XrNRA1caO4OA==,type:str]
kind: Secret
metadata:
    name: restic-repo
    namespace: vaultwarden
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWg2SmNyMHFRQ3JWZUV0
            TXBsNGxXMTBzdkxYTzBVYXRWQk51SWw3VDNJClRFQjg1VlNnTXNtTWVKMlhCazJx
            NkNTK0Q4ZmdzQ1M1SmNIdzN2bUhCSmsKLS0tIHRTdGxGNjZHOGhJM0M5R3l3dXdh
            bWdtZGtOR3p1M3FQaVpta2F1ck5aWkUKfOOSjHl6uaaUnLxkIrxdIOUdk6FLT9hV
            CChkPqLlZXyhr9oUGyy71SbG6Mdnc4JTde9FA+Qakt+9IpgmVwFxcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T18:06:15Z"
    mac: ENC[AES256_GCM,data:CLXi18gEgsrzHS8PY6lZB/QbXUILA4FX8bZIiwBbBHaZ6KUcc7kDvLUUq+ODkiLwlp7o+6tRhoUrZwB1IZ2vPsE16BxTzyMZGV5A7lq4VLr9fpLW7W7zGEEKzrs85MYsco7plkNCIb26+fxOEHaHIh1znY9B6nKIOoFMgHyb7Vk=,iv:oFrTf7XA12VpcKhZRx9NRchvRfyY6bzwKiMRjuQ3U4g=,tag:EB3B5aSxSNRv59TeJFUGKA==,type:str]
    version: 3.13.3
