apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:28+O7KYzgI9zTOP3VNSbA1/JgZCVYhU9Gu8/PA==,iv:ufwH5YlH+dMcXq67EQeTNWeqPa5XJNubnK8+9CNogz4=,tag:C7lub+CzFQvJ8CFPqMWT/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:r6EpvOOEgo6TFzXfEf9483a1oBdQFYLVHYbzWR7LVpdK9OWl2Q7BOn7egNw9t9cEhwOtq/Gj8RE=,iv:UFQE0kfMbzkIv4qX8sLNP6UOVx91T9nFR5JnO+SwBHc=,tag:vAe0WP7WEYcJJ1cZl+pnxg==,type:str]
    HC_PRUNE_URL: ENC[AES256_GCM,data:tsQ3fJmDYaGM+0apxbWbiEiOQaevmG167fQuRk3M/tCH1hGNcwEiw6zcKwqGdD/6lCfT97DZd+TShEcDL0BzlAl87wO+AO6ENFWbcw==,iv:hSdpzGsq0Mi7bjRwsA5U4dPsXn/KdcNq8zxA7hVTUis=,tag:el1L2bsHkPMD9E9ZpPJkAQ==,type:str]
    HC_URL: ENC[AES256_GCM,data:ThKBeqIEvawmH9Y22xLW0ZEVwT0bRWUvLiXk+TroTsxPSFki3qiq7n4ThZI4+VbB5pWA/UPAchjQtkQS/5jzZuBZWofSInfESYZCrw==,iv:0htDFHhIdr8wZ5ldz8jrOqgD1j8VOBYn6LZb8KmGDB8=,tag:w07nMh4d8TGMVP0xdIIsZw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OAySREHNGgUidH8yx9cg2Qw6SaFNer/YeEnNQ9XAObe43a7yrJDU80KxjqPRGnnfcbjbGtdnW2Pu4WBf,iv:uNkwP9QaacJ4yzP9eowkDOi33vm1K93lDDXA3MMT1eI=,tag:Tcxm5WNkR8hQQpDhJ/w/Dg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gpjOgpb2tmGoXuVlWmLvvFGaDQu/LdN6g4UYQjvlgyffacdUJ1Ao06vYEnroJxqngbKgTSmri4orOVeXy9cEO1RTgz/FywvBLwskUL+891Iqb3C0,iv:uHz9DuXHgHXjGhpUaJHdvCZVFzF0RbUM513SM8FBZvQ=,tag:5qfYJrVO35XrNRA1caO4OA==,type:str]
kind: Secret
metadata:
    name: restic-repo
    namespace: vaultwarden
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWg2SmNyMHFRQ3JWZUV0
            TXBsNGxXMTBzdkxYTzBVYXRWQk51SWw3VDNJClRFQjg1VlNnTXNtTWVKMlhCazJx
            NkNTK0Q4ZmdzQ1M1SmNIdzN2bUhCSmsKLS0tIHRTdGxGNjZHOGhJM0M5R3l3dXdh
            bWdtZGtOR3p1M3FQaVpta2F1ck5aWkUKfOOSjHl6uaaUnLxkIrxdIOUdk6FLT9hV
            CChkPqLlZXyhr9oUGyy71SbG6Mdnc4JTde9FA+Qakt+9IpgmVwFxcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12mpq9jh86v2jrttmjqjmw2xfkcs98s8555cr2nz8654w4rwjs3ms8293q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:58:59Z"
    mac: ENC[AES256_GCM,data:561y2fyfzasTEn6RqBbo+wfEzx0sU3Jp3LSLEANsJ3dr8d160L5vjBnxgIxTXyFbBU5sk/jzW2rQZD1qS7LQJPx0M5UUZr+qLs4zkdnBnRz+CscmHj6oHO3A9eq8NfaGVsygxa7aM5eKjd8gF4u8UxpZXrO/BjcKzRuXfSTESoU=,iv:LBtWUpHGblO160tOKwDLBKPRYYxl63wc3+NYI7fA1+E=,tag:7bTedtwgNWK/7y9gVJxb2Q==,type:str]
    version: 3.13.3
